name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java_version: [11, 17]

    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}

      - name: Run apt-get update
        run: sudo apt-get update

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout icat-lucene
        uses: actions/checkout@v2

      - name: Run Build
        run: mvn install -Dmaven.install.skip -DskipTests

      - name: Run Unit Tests
        run: mvn test -B
