name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_tests:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 8
            experimental: false
          - version: 11
            experimental: true

    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}

      - name: Checkout icat-lucene
        uses: actions/checkout@v2

      - name: Run Build
        run: mvn install -Dmaven.install.skip -DskipTests

      - name: Run Unit Tests
        run: mvn test -B
