name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

strategy:
  fail-fast: false
  matrix:
    version: [8]
    experimental: [false]
    include:
      - version: 11
        experimental: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: 'open'
      - name: Build with Maven
        run: mvn install
