name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java_version: [11, 17]

    steps:
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}

      - name: Run apt-get update
        run: sudo apt-get update

      - name: Cache local Maven repository
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout icat-lucene
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0

      - name: Run Build
        run: mvn install -Dmaven.install.skip -DskipTests

      - name: Run Unit Tests
        run: mvn test -B
